language: python

python:
- 3.8

# Command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

# Command to deploy releases to PyPi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: addisonElliott
  on:
    tags: true
  password:
    secure: u/P4yVsjsiO+pyVCugJ0yaIywRpGd/e+LYtJxxqrprQx+Si4DTdHKpRJ09c/FGoSsAjfyImAw1ErZdRB8HNP4S906DnGBvc/FdZ0/b2+PgzOsiuItJCCBNJZY9kljrPVGCjnvIUsLwkCLDfMeZYIyEE5uGxh6DnVCOiAKRYhm4Q7KJpF0IfVdogvaM0PGsKxrdq58XXnfLPGHXcbhpd8qjXBvnKw0UiDUulBTZOpFD/NSS4VVzcFPHheqUo6x/mrj65AwdL4LRnP96ynKmF703dvPy3QD7KxcluDx2DIUQ6cgnxo4ePgSaWB1Q1biNfALMnoJgYKmNvOvswd+1Z8KbmNsuPuV7P9l0Z8JQnI5H4fsKqx2qymR3lv3IPvUeTA9XSUSQlSM318/NCwjCzPFuWJme6Edt1D1AjIZyrzlegJ3zqJY+awHdK1pgmykKoDoax0EmJH5mguZBGe/PDtHFQk5WNqzF8talpAnhvboLtyuG1MRT36osjy8vaMdrE6/FRzwQp8foJtMeXP2L+fjpK5RYpi7ETj+Hlz2NPv3z6E/KfwfLYnx0EsgGP5lwTeoApcFdYqjy7TB7W9rwyU5irJgT6wbqnjIV3kvElxAc5EJNj4KYkO9L4TDJXbbTGKzrTTFFELtHOi2V2XUze2++utRhfovUTnAnaLATWd89g=

after_success:
  - codecov

# Only build for master branch and tagged released (must follow semantic versioning syntax)
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/